name: Build Windows EXE

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v3

    - name: 设置 Python 环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip==24.0
        pip install -r requirements.txt
        pip install pyinstaller

    - name: 清理旧的构建文件
      run: |
        Remove-Item -Recurse -Force build, dist
        if (Test-Path main.spec) { Remove-Item -Force main.spec }

    - name: 打包为 EXE
      run: |
        pyinstaller --onefile --windowed main.py --hidden-import=sqlalchemy_mate --hidden-import=uszipcode --hidden-import=pytz --hidden-import=sqlalchemy

    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: ZipTimezone-win-exe
        path: dist/main.exe

    - name: 发布 Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/main.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
